### ISSUE TITLE
📃: Best Time to Buy and Sell Stock using Greedy Approach => LeetCode Problems

### ISSUE THREAD

**Issue by Saiharitha3** [abhisek247767/LeetCode2024-6Companies30Days#109]
🟢 Title : Best Time to Buy and Sell Stock - Optimize for Large Inputs
🟢 Programming language : Python
🟢 Objective :
Implement an efficient algorithm to maximize profit from buying and selling a stock on different days
🟢 Summary :
The naive solution with O(n²) time complexity results in Time Limit Exceeded (TLE) errors on larger datasets. The goal is to replace the nested loops with an O(n) greedy algorithm 

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Sai Haritha Sardena

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey😍. 
Enjoy! 😎

**Comment by Saiharitha3** [comment]
Hi @abhisek247767 

I like to provide solution for this problem please assign to me and please add hacktoberfest label to this one,
Thank You.

**Comment by abhisek247767** [comment]
Assigned

**Comment by Saiharitha3** [comment]
please review PR #115

**Comment by Saiharitha3** [comment]
please review #116
