### ISSUE TITLE
📃: Adding House Robber Problem using memoization ->Leetcode problem

### ISSUE THREAD

**Issue by Salonisaroha** [abhisek247767/LeetCode2024-6Companies30Days#111]
🟢 Title : House Robber
🟢 Programming language : C++
🟢 Objective : Optimized Solution
🟢 Summary :
 Finding the maximum amount of money that can be robbed from a list of houses, where adjacent houses cannot be robbed on the same night to avoid alerting the police.

✅ Details to Include When Taking the Issue:
Name : Saloni

I am contributing In this repository  as a part of the **Hacktoberfest.**

**Comment by hrishi0902** [comment]
Hey, I am interested kindly assign `House Robber Problem`

**Comment by hrishi0902** [comment]
Can I do it in java language ? or have to do it in c++ only
