### ISSUE TITLE
📃: Palindrome Number -> Leetcode #9

### ISSUE THREAD

**Issue by Sophyia7** [abhisek247767/LeetCode2024-6Companies30Days#127]
🟢 Title : Palindrome Number
🟢 Programming language : Python
🟢 Objective : Check if a given integer reads the same forward and backward.
🟢 Summary : A number is a palindrome if it remains unchanged when its digits are reversed. For example, 121 is a palindrome, but 123 is not.
In my approach, I will convert the number to a string and create a reverse then compare the original string with its reversed version to determine if it's a palindrome.

Please merge it under the tags of hacktoberfest2024 and hactoberfest-accepted. 
***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Sophia Iroegbu

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey😍. 
Enjoy! 😎

**Comment by abhisek247767** [comment]
Assigned
