### ISSUE TITLE
📃: Valid Parentheses -> Leetcode #20 

### ISSUE THREAD

**Issue by Sophyia7** [abhisek247767/LeetCode2024-6Companies30Days#128]
🟢 Title: Merge Two Sorted Lists
🟢 Programming language: Python
🟢 Objective: Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid. 
🟢 Summary: A valid string has matching parentheses that are properly nested and closed in the correct order. This includes characters like '()', '[]', and '{}'. 
My approach is to keep track of opening parentheses using a stack, push an opening bracket onto the stack and pop when encountering a matching closing bracket, and ensure the stack is empty at the end to verify that all parentheses are matched properly. 

Please merge it under the tags hacktoberfest2024 and hactoberfest-accepted.
***********************************************************************

✅ Details to Include When Taking the Issue:
Name: Sophia Iroegbu

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey😍. 
Enjoy! 😎

**Comment by abhisek247767** [comment]
Assigned
