### ISSUE TITLE
Reverse Pairs.

### ISSUE THREAD

**Issue by shubhamjain1402** [abhisek247767/LeetCode2024-6Companies30Days#130]
🟢 Title :Reverse Pairs
🟢 Programming language :C++
🟢 Objective :To return number of reverse pairs in an array.
🟢 Summary :
Given an integer array nums, return the number of reverse pairs in the array.

A reverse pair is a pair (i, j) where:

0 <= i < j < nums.length and
nums[i] > 2 * nums[j].

PR[#129]
Please review the code under hacktoberfest

**Comment by abhisek247767** [comment]
Assigned
