### ISSUE TITLE
📃: Nearest multiple of 10

### ISSUE THREAD

**Issue by yesiamrajeev** [abhisek247767/LeetCode2024-6Companies30Days#133]
🟢 Title :Nearest multiple of 10
🟢 Programming language : java
🟢 Objective : To find nearest multiple of 10 
🟢 Summary : There is a number given we have find its nearest multiple of 10. For example if a number is 18 so it's nearest multiple would be 20 then print 20.

I want you to assign this issue to me!!

**Comment by abhisek247767** [comment]
Assigned

**Comment by yesiamrajeev** [comment]
Thank you sir!!
