### ISSUE TITLE
📃:  Count Odd Numbers in an Interval Range(Leetcode:1523)

### ISSUE THREAD

**Issue by Amer-Mukhtar** [abhisek247767/LeetCode2024-6Companies30Days#146]
🟢 Title :Count Odd Numbers in an Interval Range
🟢 Programming language :C++
🟢 Objective : Count Odd Numbers in an Interval Range
🟢 Summary : Given two non-negative integers low and high. Return the count of odd numbers between low and high(inclusive).

Link: https://leetcode.com/problems/count-odd-numbers-in-an-interval-range/description/
***********************************************************************

@abhisek247767 can you please assign this to me? with hacktoberfest labels?

**Comment by abhisek247767** [comment]
Assigned. Please check guidelines then do PR.
