### ISSUE TITLE
📃: 994. Rotting Oranges

### ISSUE THREAD

**Issue by Unnati2603** [abhisek247767/LeetCode2024-6Companies30Days#160]
🟢 Title : Rotting Oranges
🟢 Programming language : C++ 
🟢 Objective : To determine the minimum number of minutes that must elapse until no cell has a fresh orange
🟢 Summary : Given an m×n grid with empty cells (0), fresh oranges (1), and rotten oranges (2), use BFS to determine the minimum minutes until no fresh oranges remain. Each minute, fresh oranges adjacent to rotten ones become rotten.

***********************************************************************

✅ Details to Include When Taking the Issue: Return -1 if impossible
Name : Unnati

***********************************************************************

Happy Contributing! 🚀

Wishing you all the best on your open source journey😍. 
Enjoy! 😎

**Comment by Unnati2603** [comment]
Can you assign me this? with the hacktoberfest label

**Comment by abhisek247767** [comment]
And today is last day. Please do push code before 7:30 pm otherwise not possible to merge within today. Hope you understand. Happy coding. please star the repo and follow me in GitHub.
