### ISSUE TITLE
Customize my Readme File

### ISSUE THREAD

**Issue by abhisek247767** [abhisek247767/LeetCode2024-6Companies30Days#5]
Please add some necessary customization to the README file, so that other people can contribute to my repository.
Thanks in advance !!

**Comment by kanikaa-3018** [comment]
hey @abhisek247767 i am willing to do this task, please assign me for hacktoberfest24

**Comment by abhisek247767** [comment]
Done please do it .

**Comment by kanikaa-3018** [comment]
i have done it, will send the pull request on october 1st
