### ISSUE TITLE
Dynamic Road Network Management

### ISSUE THREAD

**Issue by madhura-ingole** [abhisek247767/LeetCode2024-6Companies30Days#54]
Problem Statement: You are responsible for managing a dynamic road network in a city. The city has intersections represented as nodes and roads as weighted edges (representing time to travel between intersections). Roads can be constructed or destroyed dynamically over time. You need to develop a system that:

Efficiently updates the road network when a road is added or removed.
Finds the shortest path between two intersections after each update.
Handles multiple queries for shortest paths in real time.

**Comment by madhura-ingole** [comment]
@abhisek247767 assign me this under hacktoberfest label

**Comment by madhura-ingole** [comment]
@abhisek247767 assign me this under hacktoberfest issue

**Comment by madhura-ingole** [comment]
@abhisek247767 I want to work on this

**Comment by abhisek247767** [comment]
Assigned

**Comment by madhura-ingole** [comment]
Resolve in #69
