### ISSUE TITLE
Optimized Warehouse Fulfillment

### ISSUE THREAD

**Issue by madhura-ingole** [abhisek247767/LeetCode2024-6Companies30Days#55]
Problem Statement: A warehouse stores n types of products, each with a different weight and value. You are tasked with selecting products to fulfill orders. Each order requests a specific number of items with a total weight limit. Your job is to:

Select the set of products that maximizes the total value while respecting the weight limit.
Handle multiple orders dynamically, where each order may have different weight limits and product requirements.
Ensure that product selection is optimized for different orders arriving in real time.

**Comment by madhura-ingole** [comment]
@abhisek247767 assign me this under hacktoberfest issue

**Comment by madhura-ingole** [comment]
@abhisek247767 assign me this under hacktoberfest issue

**Comment by madhura-ingole** [comment]
@abhisek247767 I want to work on this

**Comment by abhisek247767** [comment]
Do work

**Comment by madhura-ingole** [comment]
Resolved in #70
