### ISSUE TITLE
spiral matrix

### ISSUE THREAD

**Issue by Shrutibansal22** [abhisek247767/LeetCode2024-6Companies30Days#61]
@abhisek247767 
Kindly assign me this issue under hacktober fest 2024

**Comment by abhisek247767** [comment]
Done @Shrutibansal22 . Before do the PR please check the guidelines

**Comment by Shrutibansal22** [comment]
ok sure

**Comment by priyamshukla-coder** [comment]
Hi @abhisek247767 

Please assign this issue to me .
Thanks
