### ISSUE TITLE
Proposal to add "construct binary tree from pre-order and in-order traversal " problem 

### ISSUE THREAD

**Issue by Amit-yadav099** [abhisek247767/LeetCode2024-6Companies30Days#66]
I want to add "construct binary tree from pre-order and in-order traversal " problem in your c++ folder.
As a beginner ,kindly add this program under the hacktoberfest2024 

problem statment:
Given two integer arrays preorder and inorder where preorder is the preorder traversal of a binary tree and inorder is the inorder traversal of the same tree, construct and return the binary tree.

example testcase:
Input: preorder = [3,9,20,15,7], inorder = [9,3,15,20,7]
Output: [3,9,20,null,null,15,7]
here is the link of given formed tree:
(https://github.com/user-attachments/assets/98862823-ec43-4a21-93ed-edf9f673435f)

**Comment by abhisek247767** [comment]
Done. Before first star the repo and follow me for motivation.
Happy: learning
