### ISSUE TITLE
📃: Adding Kadane's Algorithms

### ISSUE THREAD

**Issue by akshit397a** [abhisek247767/LeetCode2024-6Companies30Days#86]
🟢 Title : Kadane's Algorithms
🟢 Programming language : C++
🟢 Objective : Finds the maximum sum of a contiguous subarray in linear time.
🟢 Summary : This C++ code uses Kadane's Algorithm, which efficiently finds the maximum sum of a contiguous subarray in linear time. 
      It initializes two variables to track the current maximum sum and the global maximum sum as it iterates through the array. 
      The algorithm updates these values based on the current element and returns the maximum found.

***********************************************************************

✅ Details to Include When Taking the Issue:
Name : Akshit Agarwal (akshit397a)

***********************************************************************

**Comment by helloshalini** [comment]
Hey @abhisek247767 ,
I want to work on this issue please assign to me.

**Comment by helloshalini** [comment]
Hey @abhisek247767 ,
I want to work on this issue could you please assign to me.

**Comment by akshit397a** [comment]
Hey @abhisek247767 ,
I have raised a PR on this issue kindly review.
